### ISSUE TITLE
legacy 이름공간 

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#214]
"자유게시판", "자유게시판토론", "가입인사게시판", "가입인사게시판토론"을 어떻게든 해야합니다.

#### TODOs

- [x] `*게시판토론:$1` 문서를 `*게시판:$1/댓글`로 이동
- [x] `*게시판토론:$1` 문서에서 `*게시판:$1/댓글`를 불러올 수 있도록 위키에서 내용 수정
- [x] `*게시판` 이름공간에서 `페미위키` 이름 공간 어딘가로 이동(그냥 놔둘 경우 일반 이름공간으로 처리되어 "특수:임의문서"에 잡힘 &rarr; 그렇지는 않은 것 같기도 합니다...하여튼 그대로 있으면 이상하긴 합니다.)
- [x] LocalSettings.php에서 이름공간 선언들 삭제
- [x] 이전 문서 위치로 향해있는 링크들 수정하기
- [x] legacy 이름공간에 있는 넘겨주기 문서들 삭제하기

**Comment by lens0021** [comment]
```sql
SELECT /* SLOW_OK */
       *
       FROM pagelinks
       WHERE    pl_namespace = 3902
             OR pl_namespace = 3903
             OR pl_namespace = 3904
             OR pl_namespace = 3905;
```

위와 같이 쿼리를 실행했을 때 나온 다음 문서의 링크를 페미위키 이름공간 아래 링크로 수정했습니다.

- https://femiwiki.com/w/특수:넘겨주기/page/11305
- https://femiwiki.com/w/특수:넘겨주기/page/8133
- https://femiwiki.com/w/특수:넘겨주기/page/10354
- https://femiwiki.com/w/특수:넘겨주기/page/10970
- https://femiwiki.com/w/특수:넘겨주기/page/12460
- https://femiwiki.com/w/특수:넘겨주기/page/2426
- https://femiwiki.com/w/특수:넘겨주기/page/4979
