### ISSUE TITLE
AWS extension

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#235]
```
sudo apt-get install -y python3.4-venv
python3 -mvenv ~/awscli-venv
. ~/awscli-venv/bin/activate
pip install --upgrade pip
pip install awscli

aws s3 sync /var/www/femiwiki.com/images/temp s3://femiwiki-uploaded-files-temp
aws s3 sync /var/www/femiwiki.com/images/thumb s3://femiwiki-uploaded-files-thumb
for i in archive 0 1 2 3 4 5 6 7 8 9 a b c d e f; do
  aws s3 sync /var/www/femiwiki.com/images/$i s3://femiwiki-uploaded-files/$i
done
# NOTE: deleted 디렉토리는 폴더 구조가 달라서.. 신경써서 올려야한다.

deactivate
rm -rf ~/awscli-venv
sudo apt-get autoremove --purge -y python3.4-venv
```

#### TODOs
 - [x] arn:aws:iam::302617221463:policy/AmazonS3Access 폴리시 생성
 - [x] arn:aws:iam::302617221463:role/AmazonS3Access 롤 생성
 - [x] 테스트서버에 인스턴스 프로파일 부여
 - [x] 실서버에 인스턴스 프로파일 부여
 - [x] 업로드 제한 걸기, 공지 쓰기
 - [x] `archive` 업로드하기
 - [x] `temp` 업로드하기
 - [x] `thumb` 업로드하기
 - [x] 실제 파일들 업로드하기
 - [x] 컴포저 설치, 익스텐션 설치
 - [x] 익스텐션 활성화하고 정상작동여부 테스트
 - [x] 컴포저 및 컴포저 캐시 삭제
 - [x] AWS CLI 삭제
 - [x] 업로드 제한 풀기, 업로드 테스트하기
 - [x] 공지 내리기
 - [x] S3로 업로드된 모든 파일들 및 `/var/www/femiwiki.com/images/deleted` 백업하기
 - [x] `/var/www/femiwiki.com/images/deleted` 파일 백업한 뒤, 서버에서 삭제하기 → https://trello.com/c/DPzZc8PI/ 로 넘어감

#### Activity
 - 낙엽 added [this card](https://trello.com/c/Pd45fNv4) to Doing Oct 5 at 3:16 PM
 - 낙엽 joined this card Oct 5 at 3:16 PM
 - Hyeon Kim added TODOs to this card Oct 6 at 10:33 PM
 - Hyeon Kim completed AmazonS3Access 롤 생성 on this card Oct 6 at 10:34 PM
 - Hyeon Kim completed arn:aws:iam::302617221463:policy/AmazonS3Access 폴리시 생성 on this card Oct 6 at 10:34 PM
 - Hyeon Kim completed 테스트서버에 인스턴스 프로파일 부여 on this card Oct 6 at 10:35 PM
 - Hyeon Kim completed 실서버에 인스턴스 프로파일 부여 on this card Oct 6 at 10:35 PM
 - Hyeon Kim completed `archive` 업로드하기 on this card Oct 6 at 10:40 PM
 - Hyeon Kim completed `temp` 업로드하기 on this card Oct 6 at 10:40 PM
 - Hyeon Kim completed `thumb` 업로드하기 on this card Oct 6 at 10:41 PM
 - Hyeon Kim completed 실제 파일들 업로드하기 on this card Oct 6 at 10:47 PM
 - Hyeon Kim completed 컴포저 설치, 익스텐션 설치 on this card Oct 6 at 11:17 PM
 - Hyeon Kim completed 익스텐션 활성화하고 정상작동여부 테스트 on this card Oct 6 at 11:17 PM
 - Hyeon Kim completed 컴포저 및 컴포저 캐시 삭제 on this card Oct 6 at 11:18 PM
 - Hyeon Kim completed AWS CLI 삭제 on this card Oct 6 at 11:24 PM
 - Hyeon Kim completed 업로드 제한 걸기, 공지 쓰기 on this card Oct 6 at 11:24 PM
 - Hyeon Kim completed 업로드 제한 풀기, 업로드 테스트하기 on this card Oct 6 at 11:47 PM
 - Hyeon Kim completed 공지 내리기 on this card Oct 7 at 12:01 AM
 - Hyeon Kim joined this card Oct 7 at 12:19 AM
 - Hyeon Kim completed S3로 업로드된 모든 파일들 및 `/var/www/femiwiki.com/images/deleted` 백업하기 on this card Oct 7 at 12:20 AM
 - Hyeon Kim completed `/var/www/femiwiki.com/images/deleted` 파일 백업한 뒤, 서버에서 삭제하기 → https://trello.com/c/DPzZc8PI/ 로 넘어감 on this card Oct 7 at 12:20 AM
 - Hyeon Kim moved this card from Doing to Done Oct 7 at 12:20 AM
