### ISSUE TITLE
페미위키 서버인프라 현대화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#238]
#### TODO
 - [x] 어떤 어떤 서비스가 떠있는지 문서화 → 모두 도커화하여 전부 깃헙에 문서화함
 - [x] `/var/www/femiwiki.com`, `/opt/tweetbot` 등 모두 `/srv` 로 몰기 → 도커화하면서 이 문제 완전히 사라짐
 - [x] 웹서버 Apache2 에서 Caddy로 바꾸기
 - [x] 서버 배포판 Ubuntu 14.04 LTS에서 18.04 LTS 혹은 데비안 stretch로 바꾸기 → Amazon Linux 2 사용함

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/LUriZZ7h) to To Do Apr 30 at 3:43 PM
 - Hyeon Kim joined this card Apr 30 at 3:43 PM
 - Hyeon Kim sent this card to the board Apr 30 at 3:43 PM
 - Hyeon Kim sent this card to the board Apr 30 at 3:43 PM
 - Hyeon Kim added TODO to this card Apr 30 at 3:43 PM
 - 낙엽 Jul 29 at 8:28 PM <blockquote>오래 진행되지 않아 제안/메모로 이동합니다</blockquote>
 - 낙엽 attached 페미위키:기술 to this card - Sep 1 at 12:54 PM 
 - 낙엽 Sep 1 at 12:54 PM <blockquote>[페미위키:기술](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B8%B0%EC%88%A0) </blockquote>
 - 낙엽 transferred this card from FEMIWIKI Sep 11 at 2:09 AM
 - 낙엽 completed 웹서버 Apache2 에서 Caddy로 바꾸기 on this card Oct 12 at 10:11 PM
 - Hyeon Kim completed 서버 배포판 Ubuntu 14.04 LTS에서 18.04 LTS 혹은 데비안 stretch로 바꾸기 → Amazon Linux 2 사용함 on this card Dec 22 at 10:13 PM
 - Hyeon Kim completed /var/www/femiwiki.com, /opt/tweetbot 등 모두 /srv 로 몰기 → 도커화하면서 이 문제 완전히 사라짐 on this card Dec 22 at 10:14 PM
 - Hyeon Kim completed 어떤 어떤 서비스가 떠있는지 문서화 → 모두 도커화하여 전부 깃헙에 문서화함 on this card Dec 22 at 10:14 PM
 - Hyeon Kim Dec 22 at 10:14 PM <blockquote>도커화까지 마치면서 대부분 끝남</blockquote>
 - Hyeon Kim moved this card from Backlog to 완료 Dec 22 at 10:14 PM
