### ISSUE TITLE
미디어위키 1.32 업그레이드

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#250]
2019년 1월 11일(UTC) 미디어위키 1.32.0이 출시되었습니다. 업그레이드를 준비합니다.

- [릴리즈 노트](https://www.mediawiki.org/wiki/Release_notes/1.32)

#### TODOs
- [x] ~~공식 확장기능 tar.gz에 빠진 내용이 있어서 요청했고([코멘트](https://github.com/femiwiki/mediawiki/issues/250#issuecomment-462103003) 참고) 답변 기다리고 있음~~ 그냥 컴포저 다 돌려서 대충 해결
- [x] 호환성 확인 및 수정
  - [x] Deprecation 검토 (phpcs이나 phpunit 돌리면 리스트 나옴)
    - [x] https://github.com/femiwiki/unifiedExtensionForFemiwiki/issues/5
  - [x] 1.31 이하에서만 작동하도록 제한 두었던 코드 삭제
  - [x] 기타 확인할 것
    - [x] interface admin 권한 잘 적용되는지
    - [x] (새로 OOUI가 적용된)환경설정 안 깨지는지
- [x] 수정
  - [x] dockerfile 수정
  - ~~.travis.yml 수정: Matrix 기능 써서 1.31 1.32 동시에 테스트돌리기~~ 그냥 다른 브런치라 각각 돌아가니까 그걸로 그냥 대체

#### 점검 시나리오

- [x] 사이트에 점검 공지 올리기
- [x] 데이터베이스 잠그기(~~정기 백업인 오전 6시 직전에 잠그면 좋음~~ &rarr; 정기 백업은 5시였음)
- [x] 파일 업로드 막기
- [x] 데이터베이스 백업(혹은 [백업 확인](https://s3.console.aws.amazon.com/s3/buckets/femiwiki-backups/?region=ap-northeast-1&tab=overview))
- [x] 미디어위키 서버에서 git pull
- **다운타임 시작**
- [x] `docker stack rm mediawiki` (아래를 위함)
- [x] `docker system prune --volumes --force` (1.31 소스코드가 들어있는 볼륨 mediawiki_files 등 제거)
- [x] `docker stack deploy --prune -c production.yml mediawiki`
  - 이 과정중에 데이터베이스 스키마가 1.32로 업데이트되는데 로컬에서 해봤을 때도 20분 정도 걸렸습니다.
  - 06:04 시작 &rarr; 06:11 종료
- [x] 데이터베이스 잠금 해제
- [x] update.php 실행하여 데이터베이스 스키마 업그레이드
- **다운타임 끝**
- [x] 파일 업로드 막은 것 해제
- [x] 사이트 이상 없나 확인하기
- 기타 할일
  - [x] https://github.com/femiwiki/mediawiki/issues/244#issuecomment-450847871
  - [x] https://github.com/femiwiki/Sanctions/blob/8b9e3ceef27585e0a4f336f0204ece2f94c59268/specials/SpacialSanctions.php#L59-L63 제거 &rarr; https://github.com/femiwiki/Sanctions/commit/2f86afeca628a93b407d18ecaa1bd0a800680c9b

**Comment by lens0021** [comment]
위키미디어 ExtDist의 몇 확장기능 스냅샷에 종속성 누락이 있는 것 같아 리포트했습니다. https://phabricator.wikimedia.org/T215713

**Comment by lens0021** [comment]
> 위키미디어 ExtDist의 몇 확장기능 스냅샷에 종속성 누락이 있는 것 같아 리포트했습니다. https://phabricator.wikimedia.org/T215713

위 내용은 모든 확장기능에 대해 컴포저 인스톨을 하도록 [이와 같이](
https://github.com/femiwiki/mediawiki/pull/261/commits/14314eb68e96fa363b1c1f33f2b6e94eef8b9cbb) 수정하여 일단 처리했습니다.
