### ISSUE TITLE
Discord 웹훅 설치

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#278]
zapier를 사용하여 디스코드 페미위키 채널로 바뀐글을 보내고 있는데 zapier 소모량이 많고 알림 내용을 제한하는 것이 어렵습니다. 그래서 확장 기능을 하나 써서 보내면 좋겠습니다.

#### TODOs

- [x] ~~웹훅 생성~~ 현재 사용중인 웹훅 재사용
- [x] 확장기능 설치 코드 수정 &rarr; https://github.com/femiwiki/mediawiki/commit/a4d262e9dc2f988089ca4f473a0048c83f3a7147
- [x] 확장기능 설치판 배포
- [x] 메시지 번역(한국어가 없습니다!)

#### References

- [Extension:DiscordNotifications](https://www.mediawiki.org/wiki/Extension:DiscordNotifications)

**Comment by lens0021** [comment]
단점이 스트럭처드 디스커션 관련 알림을 안 주네요(즉 토론 주제를 새로 열거나 답변을 단 경우는 안 뜹니다). 일단은 어쩔 수 없으니까 그렇다치고, 버전 관리가 깃헙인거 같으니까 고칠 수 있으면 대충 고쳐가지고 PR 넣어보든지 해보면 좋겠습니다. 원인은 이 확장기능이 알림을 주고 싶은 각종 이벤트 콜백에서 웹훅을 보낼텐데 스트럭처드 디스커션은 적당한 콜백을 제공하는 게 없어서 그런 것 같기도 하고 원래가 중소규모 위키형 확장기능이라 그냥 신경 안 쓴 거 같기도 합니다. 혹시 [APIFlowAfterExecute 훅](https://github.com/wikimedia/mediawiki-extensions-Flow/blob/e0a1cd9718a85ba9474125eea5d104ada7f26500/includes/Api/ApiFlow.php#L99)으로 되는지 싶어져서 한번 실험해보면 좋겠습니다.
