### ISSUE TITLE
미디어위키 1.34 업그레이드

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#285]
[릴리즈 노트(1.34)](https://www.mediawiki.org/wiki/Release_notes/1.34)

#### TODO

- 업그레이드 내역 검토
- `LocalSettings.php` 수정
  - [`$wgEnableSpecialMute`](https://mediawiki.org/wiki/Special:MyLanguage/Manual:%24wgEnableSpecialMute)
  - ~~`$wgSquidServersNoPurge` is renamed to `$wgCdnServersNoPurge`~~ &rarr; https://github.com/femiwiki/femiwiki/issues/93 으로 필요 없어짐
  - `$wgCookieSetOnAutoblock` and `$wgCookieSetOnIpBlock` are now enabled by default.
  - `$wgRelatedArticlesDescriptionSource = 'textextracts';`
  - ~~위키데이터 브릿지 https://github.com/femiwiki/docker-mediawiki/issues/324~~ &rarr; 연기
- 확장기능 호환성 체크
  - 자제 제작 확장기능 체크
    - Block is a deprecated alias for DatabaseBlock.
  - 서드 파티 확장기능 버전업 할 수 있는지/해야 하는지 체크
- https://github.com/femiwiki/femiwiki/issues/114
- OOUI 테마 적용 https://github.com/femiwiki/FemiwikiSkin/issues/63
- 페미위키 이슈 중 업그레이드로 해결/완화되는 것 없나 확인

#### 점검 시나리오

- [x] 점검 공지 게시
- [x] 데이터베이스 잠그기 & 파일 업로드 막기
- [x] 데이터베이스 백업(정기 백업인 5시 전후로 작업하면 생략 가능)
- [x] `git fetch && git checkout REL1_34`
- **다운타임 돌입**
- [x] `docker stack rm mediawiki`
- [x] `watch docker volume rm mediawiki_files`
- [x] 데이터베이스 잠금 해제(`update.php`실행에 필요)
- [x] 파일 업로드 허용
- [x] `docker stack deploy --prune -c production.yml mediawiki`: 이 과정 중에 데이터베이스 스키마가 업데이트되어 시간이 수분 소요 예정
- **다운타임 해제**
- [x] 상태 확인
- [x] 브랜치 다 머지하기
- [x] `git fetch master`; `git branch -D master`; `git checkout master`;
- [x] 점검 공지 내리기

**Comment by lens0021** [comment]
1.34가 곧 출시될 것으로 보여 1.33을 건너뛰게 될 수도 있을 것 같습니다 &rarr; https://phabricator.wikimedia.org/T232023

**Comment by lens0021** [comment]
1.33 이슈 다시 팠습니다 https://github.com/femiwiki/mediawiki/issues/301
