### ISSUE TITLE
미디어위키 1.33 업그레이드

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#301]
[릴리즈 노트(1.33)](https://www.mediawiki.org/wiki/Release_notes/1.33)

#### TODO

- 업그레이드 내역 검토
- LocalSettings.php 수정
- 확장기능 호환성 체크
  - 자제 제작 확장기능 체크
  - 서드 파티 확장기능 버전업 할 수 있는지/해야 하는지 체크
- 페미위키 이슈 중 업그레이드로 해결/완화되는 것 없나 확인

#### 점검 시나리오

- [x] 점검 공지 게시
- [x] 데이터베이스 잠그기 & 파일 업로드 막기
- [x] 데이터베이스 백업(정기 백업인 5시 전후로 작업하면 생략 가능)
- [x] `git pull`
- **다운타임 돌입**
- [x] `docker stack rm mediawiki`
- [x] `docker system prune --volumes --force`
- [x] 데이터베이스 잠금 해제(`update.php`실행에 필요)
- [x] `docker stack deploy --prune -c production.yml mediawiki`
  - 이 과정 중에 데이터베이스 스키마가 업데이트되어 시간이 수분 소요 예정
- **다운타임 해제**
- [x] `maintenance/migrate....php` 실행이 필요할 수 있음(https://www.mediawiki.org/wiki/Manual:$wgChangeTagsSchemaMigrationStage 참고) &rarr; update.php 실행 중 자동으로 같이 실행한 것 같음.
- [x] 파일 업로드 허용
- [x] 점검 공지 내리기
