### ISSUE TITLE
사용자 IP를 제대로 인식하지 못함

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#309]
현재 모든 사용자의 IP가 10.255.0.2에서 접속된 것으로 인식되어 자동 차단이 잘못 적용되는 등의 문제가 있습니다.

https://github.com/femiwiki/femiwiki/issues/93 이후 발생한 문제로 추정되며, 기존에 했던 [XFF 참고 설정을 지웠지만](https://github.com/femiwiki/mediawiki/commit/fe45a1d)(참고: secret.php도 동일하게 수정함) 문제가 동일합니다.

#### TODO

- [x] 제재안에 의한 자동 차단 비활성화함
- [x] IP 단위 속도제한 완화 &rarr; https://github.com/femiwiki/femiwiki/commit/5cdc9ac
- [x] 43번 필터 비활성화
- [x] 자동 차단 예외 설정 https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Autoblock_whitelist
- [x] [MediaWiki:Passwordremindertext](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Passwordremindertext) 수정
----
- [x] 문제해결
----
- [x] [제재안에 의한 자동 차단 다시 활성화하기](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Sanctions-autoblock?action=edit)
- [x] IP 단위 속도제한 재활성화(https://github.com/femiwiki/femiwiki/commit/5cdc9ac 리버트)
- [x] 43번 필터 재활성화(https://femiwiki.com/w/Special:AbuseFilter/43)
- ~~자동 차단 예외 제거(https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Autoblock_whitelist)~~ 그냥 놔둬도 될듯 어차피 내부 IP고...
- [x] [MediaWiki:Passwordremindertext](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Passwordremindertext) 수정

**Comment by lens0021** [comment]
https://github.com/femiwiki/mediawiki/commit/d282795 에서 같이 추가한 [$wgUsePrivateIPs](https://www.mediawiki.org/wiki/Manual:$wgUsePrivateIPs)도 지우겠습니다. 마찬가지로 XFF 관련 설정입니다.

[업데이트] https://github.com/femiwiki/mediawiki/commit/9eb7446 적용했지만 문제 동일합니다.

**Comment by lens0021** [comment]
```
Ignoring unsupported options: network_mode
```
https://github.com/femiwiki/mediawiki/commit/08851fd 시도해보았다가 위와 같이 나와서 다시 master branch로 돌렸습니다.

**Comment by lens0021** [comment]
docker-compose를 잠깐 쓴다 OR 쿠버네티스로 갈아탈 때까지 이 문제를 쌩깐다(대신 그럼 IP 차단이나 '모르는 아이피에서 접속 알림', IP에 대한 속도 제한을 못 하는 상태가 유지됨) 중 하나를 결정해야 겠습니다

**Comment by simnalamburt** [comment]
Lens0021은 임시로 docker-compose로 바꾸는걸 시도하고, simnalamburt는 k3s로 넘어가는걸 시도하기로함

**Comment by lens0021** [comment]
시험해보니 도커에서 network mode를 host로 한 경우에 기존에 쓰던 alias(`http://mysql`나 `http://parsoid`) 같은 것을 못 쓰는 것 같은데 해결책이 뭘까요 :sob:

**Comment by lens0021** [comment]
> Lens0021은 임시로 docker-compose로 바꾸는걸 시도하고, simnalamburt는 k3s로 넘어가는걸 시도하기로함

도커로 하려면 웹 서버가 리버스 프록시를 쓰든지 하는 간단하지 않은 방법으로 해결해야 하여 k3s를 도입할 때까지 연기되었습니다

**Comment by lens0021** [comment]
Nomad로 이동 중에, CPU 문제로 [Consul connect](https://www.nomadproject.io/docs/integrations/consul-connect)를 사용하지 않으려다 보니 웹서버가 host network를 써서 이 문제가 완화됐습니다. 나중에 Consul connect를 쓰게 될 땐 유념해서 프록시를 넣든가 어떻든가 잘 설정해야 하겠습니다.

**Comment by lens0021** [comment]
관련 커밋은 https://github.com/femiwiki/nomad/commit/1e79b4531992acf16faf86580a1f857f0a5b1a98 입니다
