### ISSUE TITLE
Vagrant를 Docker로 교체

### ISSUE THREAD

**Issue by choidamdam** [femiwiki/docker-mediawiki#68]
현행 Vagrant 기반 배포 프로세스가 단일 개발자/머신만을 고려하고 있으므로 이를 개선할 필요가 있음

**Comment by lens0021** [comment]
(참고: Docker화는 simnalamburt님이 진행중입니다)

제가 만든 비공식 확장기능 중에 "Sanctions"라는 이름으로 돼있는 확장기능은 https://github.com/lens0021/Sanctions 이쪽에서 가져오도록 변경해 주세요! 근데 제 이름 아래 있는게 조금 그러면 femiwiki/Sanctions로 옮길게요 어떤게 좋을까요? @simnalamburt

**Comment by simnalamburt** [comment]
@lens0021 femiwiki 그룹으로 transfer 해주세요

**Comment by simnalamburt** [comment]
### Dockerization TODOs
- [x] ~Install PEAR's Mail~
  - 이제 자동으로 깔림. https://github.com/wikimedia/mediawiki/commit/ee5a9b78 참고
- [x] `/var/spool/cron/crontabs/root` 
  - 루트계정의 크론탭. 매일 06:10 시에 `/opt/femiwiki/generate_sitemap.sh`를 실행하도록 되어있음. https://www.mediawiki.org/wiki/Manual:GenerateSitemap.php 참고
- [x] tini 넣어야함
- [x] `/var/www/femiwiki.com` 안에있는 파일들 확인
- [x] `/opt/femiwiki` 안에있는 파일들 확인: secret.php 만 하면 끝남
  - `/opt/femiwiki/LocalSettingsSecure.php` 이 위치 마음에 안듦 → `/tmp/secret.php` 사용
- [x] imagemagick을 설치하기
- [x] ~install.php 실행할때 `/srv/femiwiki.com/LocalSettings.php` 가 존재하면 안되는지~ → 중요하지 않은 문제임. 현행 유지함
- [x] Avoid running Composer as root. See https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md → `www-data` 유저인 상태에서 실행하도록 수정함
- [x] ~`HEALTHCHECK` 넣기~ → FastCGI 서버라서 헬스체크하기 난감함. 포기
- [x] `RUN rm -rf /tmp/composer`
- [x] `/srv/femiwiki.com` 밑의 모든것들 소유자가 `www-data`인지 확인
- [x] `secret.php`를 도커 빌드시점이 아니라 실행 시점에 넣어주도록 고쳐야함

### Docker Swarm TODOs
- [x] [memcached](https://hub.docker.com/_/memcached) 같이 띄워주기, LocalSettings.php 고쳐서 memcached 올바르게 가리켜주기
- [x] Parsoid도 같은 femiwiki web 서버에 넣기 (오토스케일링 시 웹 서버가 여럿이 될 수 있는데 이 때 각 서버마다 parsoid가 하나씩 있는 상태가 목표)

### Checklist
- [x] https://femiwiki.com/sitemap/sitemap-index-femiwiki.xml 가 잘 열리는지 확인
- [x] 모든 익스텐션 다 잘 설치되었는지 확인 &rarr; https://github.com/femiwiki/mediawiki/issues/68#issuecomment-447724323
- [x] 기타 기능들 테스트 &rarr; https://github.com/femiwiki/mediawiki/issues/68#issuecomment-447724323

**Comment by lens0021** [comment]
- [ ] Parsoid도 같은 femiwiki web 서버에 넣기 (오토스케일링 시 웹 서버가 여럿이 될 수 있는데 이 때 각 서버마다 parsoid가 하나씩 있는 상태가 목표)

**Comment by lens0021** [comment]
트렐로에 적었다가 옮겨서 상세히 적습니다
### 수정 필요
- [x] SyntaxHighlighting 확장기능이 적용되지 않음: python3가 없어서 생긴 문제로 보이며 `apt-get install python3 update && apt-get install python3` 실행 후에는 해당 확장기능이 작동함을 확인하였습니다.
- [x] S3에 첨부파일 이미지가 업로드되지 않음: Extension:AWS를 위해 IAM User를 만들어 aws_access_key_id, aws_secret_access_key 같은 것들을 secret.php에 추가해야함

### 정상 작동 확인함
- 로그인
- 회원가입
- 이메일 인증하기
- 사용자 문서에서 다른 사용자에게 이메일 보내기
- 특수문서 https://github.com/femiwiki/mediawiki/issues/179 이슈
- 시각편집기 시동
- 시각편집기로 편집하기
- 설치된 모든 확장기능들의 기본적인 작동여부
### 생략된 테스트
- [x] X-Forwarded-For 정상 처리 여부(https://github.com/femiwiki/mediawiki/issues/178): 테스트 방법은 자기 자신에 대한 사용자 검사를 실행하여 IP가 올바르게 표시되는지 확인. 프록시(로드밸런서) 환경 하에서 테스트하여야 하여 생략함
- [x] ~파일 업로드, 이미지 로딩 등 S3 관련: 테스트용 S3 Bucket을 생성하지 않아서 생략함~ &rarr; 처리함

@simnalamburt
